FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

CMD [ "npm" ,"run","start"]

# docker container run -it -p 3001:3001  -v /Users/minhajuddinquazi/CodeSpace/Docker/apps/app3:/app/app3  node:alpine bash